version: "3.6"

services:
  marklogic:
    image: marklogic.azurecr.io/marklogic:latest
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "7997-8020:7997-8020/tcp"

  data-hub:
    image: marklogic.azurecr.io/marklogic/data-hub:3.0.0
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/app
    environment:
      SERVER_PORT: 8080

  gradle:
    image: gradle:alpine
    depends_on:
      - marklogic
    volumes:
      - type: bind
        source: $PWD
        target: /home/gradle/project
    working_dir: /home/gradle/project
    command: "gradle mlInit mlInstallAdmin mlDeploy -PmlHost=marklogic -PmlUsername=admin -PmlPassword=admin"

volumes:
  marklogic_data:
